# FantasyPros name : ESPN name
NAME_CORRECTIONS = {
    'Benny Cunningham': 'Benjamin Cunningham',
    'Cecil Shorts': 'Cecil Shorts III',
    'Christopher Ivory': 'Chris Ivory',
    'E.J. Manuel': 'EJ Manuel',
    'Gator Hoskins': 'Harold Hoskins',
    'Josh Cribbs': 'Joshua Cribbs',
    'Matt Slater': 'Matthew Slater',
    'Mickey Shuler': 'Mickey Charles Shuler',
    'Robert Griffin III': 'Robert Griffin',
    'Robert Housler': 'Rob Housler',
    'Steve Johnson': 'Stevie Johnson',
    'Taylor Yates': 'T.J. Yates',
    'Timothy Wright': 'Tim Wright',
    'Will Tukuafu': "Will Ta'ufo'ou",
    'D.K. Metcalf':'DK Metcalf'
}

COLUMN_MAPPINGS = {
    'QB': {
        'Player': 'PLAYER',
        'ATT': 'PASS_ATT',
        'TDS': 'PASS_TD',
        'YDS': 'PASS_YDS',
        'ATT.1': 'RUSH_ATT',
        'TDS.1': 'RUSH_TD',
        'YDS.1': 'RUSH_YDS',
        'CMP': 'CMP',
        'FG': 'FG',
        'FGA': 'FGA',
        'FL': 'FL',
        'FPTS': 'FPTS',
        'INTS': 'INTS',
        'Player': 'Player',
        'REC': 'REC',
        'XPT': 'XPT',
        'position': 'POSITION',
        'week': 'WEEK',
        'expert': 'EXPERT'
    },
    'RB': {
        'Player': 'PLAYER',
        'ATT': 'RUSH_ATT',
        'YDS': 'RUSH_YDS',
        'TDS': 'RUSH_TD',
        'ATT.1': 'PASS_ATT',
        'YDS.1': 'REC_YDS',
        'TDS.1': 'REC_TD',
        'CMP': 'CMP',
        'FG': 'FG',
        'FGA': 'FGA',
        'FL': 'FL',
        'FPTS': 'FPTS',
        'INTS': 'INTS',
        'Player': 'Player',
        'REC': 'REC',
        'XPT': 'XPT',
        'position': 'POSITION',
        'week': 'WEEK',
        'expert': 'EXPERT'
    },
    'WR': {
        'Player': 'PLAYER',
        'ATT': 'RUSH_ATT',
        'TDS': 'RUSH_TD',
        'YDS': 'RUSH_YDS',
        'ATT.1': 'PASS_ATT',
        'TDS.1': 'REC_TD',
        'YDS.1': 'REC_YDS',
        'CMP': 'CMP',
        'FG': 'FG',
        'FGA': 'FGA',
        'FL': 'FL',
        'FPTS': 'FPTS',
        'INTS': 'INTS',
        'Player': 'Player',
        'REC': 'REC',
        'XPT': 'XPT',
        'position': 'POSITION',
        'week': 'WEEK',
        'expert': 'EXPERT'
    },
    'TE': {
        'Player': 'PLAYER',
        'ATT': 'RUSH_ATT',
        'TDS': 'REC_TD',
        'YDS': 'REC_YDS',
        'ATT.1': 'PASS_ATT',
        'TDS.1': 'RUSH_TD',
        'YDS.1': 'RUSH_YDS',
        'CMP': 'CMP',
        'FG': 'FG',
        'FGA': 'FGA',
        'FL': 'FL',
        'FPTS': 'FPTS',
        'INTS': 'INTS',
        'Player': 'Player',
        'REC': 'REC',
        'XPT': 'XPT',
        'position': 'POSITION',
        'week': 'WEEK',
        'expert': 'EXPERT'
    },
    'K': {
        'Player': 'PLAYER',
        'ATT': 'RUSH_ATT',
        'TDS': 'REC_TD',
        'YDS': 'REC_YDS',
        'ATT.1': 'PASS_ATT',
        'TDS.1': 'RUSH_TD',
        'YDS.1': 'RUSH_YDS',
        'CMP': 'CMP',
        'FG': 'FG',
        'FGA': 'FGA',
        'FL': 'FL',
        'FPTS': 'FPTS',
        'INTS': 'INTS',
        'Player': 'Player',
        'REC': 'REC',
        'XPT': 'XPT',
        'position': 'POSITION',
        'week': 'WEEK',
        'expert': 'EXPERT'
    },
'DST': {
        'Player': 'PLAYER',
        'FPTS': 'FPTS',
        'Player': 'Player',
        'position': 'POSITION',
    }
}